import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import "./globals.css";

const barlow = Barlow({
    subsets: ["latin"],
    weight: ["300", "400", "600", "900"],
});

export const metadata: Metadata = {
    title: "Gengis - 3D Artist",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={barlow.className}>{children}</body>
        </html>
    );
}
